# Basis-Image mit Node 18
FROM node:18

# Arbeitsverzeichnis im Container
WORKDIR /app

# Nur package-Dateien kopieren und installieren
COPY package*.json ./
RUN npm install --omit=optional

# Rest des Projekts kopieren
COPY . .

# Port für Vite Dev-Server öffnen
EXPOSE 5173

# Direkt vite starten
CMD ["npx", "vite", "--host"]
